# Generated by Django 3.1.12 on 2025-07-18 05:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('em_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('em_name', models.CharField(max_length=100)),
                ('em_to', models.CharField(max_length=100)),
                ('em_subject', models.CharField(max_length=100)),
                ('em_message', models.TextField()),
                ('em_type', models.CharField(default='SENT', max_length=100)),
                ('em_status', models.CharField(default='NoThrash', max_length=100)),
                ('em_created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
