# Generated by Django 3.1.12 on 2025-07-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpamEmails',
            fields=[
                ('sm_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('sm_email', models.CharField(max_length=100)),
            ],
        ),
    ]
