# Generated by Django 3.1.12 on 2025-07-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_spamemails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='em_status',
            field=models.CharField(default='NoTrash', max_length=100),
        ),
    ]
