# Generated by Django 3.1.12 on 2025-07-22 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20250718_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyEmails',
            fields=[
                ('em_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('em_name', models.CharField(max_length=100)),
                ('em_to', models.CharField(max_length=100)),
                ('em_subject', models.CharField(max_length=100)),
                ('em_message', models.TextField()),
                ('em_type', models.CharField(default='SENT', max_length=100)),
                ('em_status', models.CharField(default='NoTrash', max_length=100)),
                ('em_created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='emails',
            name='em_reply',
            field=models.TextField(default=''),
        ),
    ]
