# Generated by Django 3.1.12 on 2025-07-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20250722_2149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReplyEmails',
        ),
        migrations.AddField(
            model_name='emails',
            name='em_spam',
            field=models.TextField(default='NO'),
        ),
    ]
